In [1]:
import pandas as pd
import numpy as np

In [89]:
df = pd.read_csv('data_pre_processed.csv')
df.head()

Unnamed: 0  관객 평점  전문가 평점  동영상  등급  상영 시간  제작 국가         관객수  개봉계절_봄  \
0           0   9.04    6.09   20  15  137.0      1  12186327.0       0   
1           1   7.83    5.92   17  12  139.0      1   8539495.0       0   
2           2   8.27    5.00   17  15  125.0      1   7817446.0       0   
3           3   8.37    7.00    8  12  133.0      0   7258678.0       0   
4           4   9.14    6.00   14  18  121.0      1   6879841.0       0   

   개봉계절_여름  ...  장르_뮤지컬  장르_미스터리  장르_범죄  장르_블랙코미디  장르_서스펜스  장르_스릴러  장르_애니메이션  \
0        1  ...       0        0      0         0        0       0         0   
1        0  ...       0        0      0         0        0       0         0   
2        0  ...       0        0      0         0        0       0         0   
3        1  ...       0        0      0         0        0       0         0   
4        0  ...       0        0      0         0        0       0         0   

   장르_액션  장르_코미디  장르_판타지  
0      0       0       0  
1      0       0       1  
2      1       0       0  
3      1       0       0  
4      1       0       0  

[5 rows x 30 columns]

In [90]:
y = df['관객수']
X = df.drop(['Unnamed: 0','관객수'],axis = 1)
df= df.drop(['Unnamed: 0','관객수'],axis = 1)
X.head()

관객 평점  전문가 평점  동영상  등급  상영 시간  제작 국가  개봉계절_봄  개봉계절_여름  개봉계절_가을  개봉계절_겨울  \
0   9.04    6.09   20  15  137.0      1       0        1        0        0   
1   7.83    5.92   17  12  139.0      1       0        0        0        1   
2   8.27    5.00   17  15  125.0      1       0        0        0        1   
3   8.37    7.00    8  12  133.0      0       0        1        0        0   
4   9.14    6.00   14  18  121.0      1       0        0        1        0   

   ...  장르_뮤지컬  장르_미스터리  장르_범죄  장르_블랙코미디  장르_서스펜스  장르_스릴러  장르_애니메이션  장르_액션  \
0  ...       0        0      0         0        0       0         0      0   
1  ...       0        0      0         0        0       0         0      0   
2  ...       0        0      0         0        0       0         0      1   
3  ...       0        0      0         0        0       0         0      1   
4  ...       0        0      0         0        0       0         0      1   

   장르_코미디  장르_판타지  
0       0       0  
1       0       1  
2       0       0  
3       0       0  
4       0       0  

[5 rows x 28 columns]

In [4]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 297 entries, 0 to 296
Data columns (total 28 columns):
관객 평점        297 non-null float64
전문가 평점       297 non-null float64
동영상          297 non-null int64
등급           297 non-null int64
상영 시간        297 non-null float64
제작 국가        297 non-null int64
개봉계절_봄       297 non-null int64
개봉계절_여름      297 non-null int64
개봉계절_가을      297 non-null int64
개봉계절_겨울      297 non-null int64
요일           297 non-null int64
장르_SF        297 non-null int64
장르_공포        297 non-null int64
장르_느와르       297 non-null int64
장르_다큐멘터리     297 non-null int64
장르_드라마       297 non-null int64
장르_멜로/로맨스    297 non-null int64
장르_모험        297 non-null int64
장르_뮤지컬       297 non-null int64
장르_미스터리      297 non-null int64
장르_범죄        297 non-null int64
장르_블랙코미디     297 non-null int64
장르_서스펜스      297 non-null int64
장르_스릴러       297 non-null int64
장르_애니메이션     297 non-null int64
장르_액션        297 non-null int64
장르_코미디       297 non-null int64
장르_판타지       297 non-null

In [5]:
X= X.values

In [6]:
X

array([[ 9.04,  6.09, 20.  , ...,  0.  ,  0.  ,  0.  ],
       [ 7.83,  5.92, 17.  , ...,  0.  ,  0.  ,  1.  ],
       [ 8.27,  5.  , 17.  , ...,  1.  ,  0.  ,  0.  ],
       ...,
       [ 5.18,  5.8 ,  5.  , ...,  1.  ,  0.  ,  0.  ],
       [ 7.85,  5.  ,  5.  , ...,  0.  ,  0.  ,  0.  ],
       [ 7.  ,  5.  ,  4.  , ...,  0.  ,  0.  ,  0.  ]])

In [7]:
y

0      12186327.0
1       8539495.0
2       7817446.0
3       7258678.0
4       6879841.0
5       6592151.0
6       5653270.0
7       5316325.0
8       5138193.0
9       4945484.0
10      4853778.0
11      4018035.0
12      4014293.0
13      3849087.0
14      3689325.0
15      3653238.0
16      3637122.0
17      3324861.0
18      3279296.0
19      3049894.0
20      2931897.0
21      2788732.0
22      2735721.0
23      2658589.0
24      2614601.0
25      2588617.0
26      2514943.0
27      2451919.0
28      2421011.0
29      2359174.0
          ...    
267       22518.0
268       21797.0
269       20760.0
270       20018.0
271       19986.0
272       19771.0
273       19440.0
274       19267.0
275       18740.0
276       18648.0
277       18535.0
278       18323.0
279       18247.0
280       18028.0
281       17941.0
282       17691.0
283       17222.0
284       16864.0
285       16601.0
286       16577.0
287       16515.0
288       16340.0
289       16336.0
290       15986.0
291       

# 흥행 여부 판별(KNN 사용)

In [8]:
## Import the Classifier.
from sklearn.neighbors import KNeighborsClassifier
## Instantiate the model with 2 neighbors. 
knn = KNeighborsClassifier(n_neighbors=5)
## Fit the model on the training data.


In [9]:
# 관객수 200만명 이상을 기록한 것은 36개 영화로 이 영화들을 흥행했다고 판별 
viewer_labels = np.where(y>=2000000, 1, 0)
viewer_labels

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
#model = LinearRegression(fit_intercept=False) => intercept를 사용하지 않고자 하는 경우

In [78]:
X_train, X_test, y_train, y_test = train_test_split(X, viewer_labels, test_size = 0.3)

In [79]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [80]:
X_train.shape

(207, 28)

In [81]:
X_test.shape

(90, 28)

In [82]:
y_pred = knn.predict(X_test)

In [83]:
from sklearn.metrics import confusion_matrix

In [84]:
confusion_matrix(y_test, y_pred)

array([[75,  4],
       [ 7,  4]], dtype=int64)

In [85]:
knn.score(X_test, y_test)

0.8777777777777778

# 선형 회귀 모델

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [42]:
model = LinearRegression()

In [43]:
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [44]:
model.score(X_train,y_train)

0.4131452225796711

In [45]:
model.score(X_test, y_test)

0.38009465440096757

In [86]:
model.coef_

array([  360207.3286472 ,    -5568.42356013,    83506.91809815,
          16809.93220071,    15694.6689608 ,   669332.50906145,
         -66975.16627632,   264855.99165458,   -85532.35234425,
        -112348.47303401,   353578.61256502,  -141713.38022085,
         380910.47655861,   358217.95210001, -1013438.64296341,
        -453110.17192615,  -189378.08074315,  -248565.93469717,
         312887.62946987,   117841.30750762,    53845.6546839 ,
        -100930.31691967,  -776386.83131607,  -305874.05252264,
         283802.61688001,   338210.94837874,  -831620.92680223,
        2215301.75253258])

In [91]:
df.columns

Index(['관객 평점', '전문가 평점', '동영상', '등급', '상영 시간', '제작 국가', '개봉계절_봄', '개봉계절_여름',
       '개봉계절_가을', '개봉계절_겨울', '요일', '장르_SF', '장르_공포', '장르_느와르', '장르_다큐멘터리',
       '장르_드라마', '장르_멜로/로맨스', '장르_모험', '장르_뮤지컬', '장르_미스터리', '장르_범죄',
       '장르_블랙코미디', '장르_서스펜스', '장르_스릴러', '장르_애니메이션', '장르_액션', '장르_코미디',
       '장르_판타지'],
      dtype='object')

# 비선형 회귀

In [99]:
from sklearn.preprocessing import PolynomialFeatures
polynomial = PolynomialFeatures(degree=2, include_bias=False)

In [100]:
X_test_poly = polynomial.fit_transform(X_test)

In [101]:
X_train_poly = polynomial.fit_transform(X_train)

In [102]:
X_test_poly.shape

(90, 434)

In [103]:
model_poly = LinearRegression()
model_poly.fit(X_train_poly, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [104]:
model_poly.score(X_train_poly, y_train)

0.8620774658089224

In [105]:
y_poly_hat = model_poly.predict(X_test_poly)
model_poly.score(X_test_poly, y_test)

-3.6778235991948023

In [1]:
import xgboost as xgb